In [92]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Imorting Data Set

In [93]:
df = pd.read_csv("E:\Shipment Price Prediction\Data_set/Shipment_price_prediction.csv")

df.head(10)

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,30,19,551.00,29.00,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,240,1000,6200.00,6.20,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,100,500,40000.00,80.00,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,31920,127360.80,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,38000,121600.00,3.20,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN
5,23,112-NG-T01,Pre-PQ Process,SCMS-87,ASN-57,Nigeria,PMO - US,Direct Drop,EXW,Air,...,240,416,2225.60,5.35,0.02,"Aurobindo Unit III, India",Yes,504,5920.42,NaN
6,44,110-ZM-T01,Pre-PQ Process,SCMS-139,ASN-130,Zambia,PMO - US,Direct Drop,DDU,Air,...,90,135,4374.00,32.40,0.36,MSD South Granville Australia,Yes,328,Freight Included in Commodity Cost,NaN
7,45,109-TZ-T01,Pre-PQ Process,SCMS-140,ASN-94,Tanzania,PMO - US,Direct Drop,EXW,Air,...,60,16667,60834.55,3.65,0.06,"Aurobindo Unit III, India",Yes,1478,6212.41,NaN
8,46,112-NG-T01,Pre-PQ Process,SCMS-156,ASN-93,Nigeria,PMO - US,Direct Drop,EXW,Air,...,60,273,532.35,1.95,0.03,"Aurobindo Unit III, India",No,See ASN-93 (ID#:1281),See ASN-93 (ID#:1281),NaN
9,47,110-ZM-T01,Pre-PQ Process,SCMS-165,ASN-199,Zambia,PMO - US,Direct Drop,CIP,Air,...,120,2800,115080.00,41.10,0.34,ABBVIE (Abbott) St. P'burg USA,Yes,643,Freight Included in Commodity Cost,NaN

In [94]:
df.describe().T
print(df.columns)

Index(['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country',
       'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode',
       'PQ First Sent to Client Date', 'PO Sent to Vendor Date',
       'Scheduled Delivery Date', 'Delivered to Client Date',
       'Delivery Recorded Date', 'Product Group', 'Sub Classification',
       'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage',
       'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity',
       'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site',
       'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)',
       'Line Item Insurance (USD)'],
      dtype='object')

In [95]:
df.isnull().sum()

ID                                 0
Project Code                       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                    360
PQ First Sent to Client Date       0
PO Sent to Vendor Date             0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Brand                              0
Dosage                          1736
Dosage Form                        0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
Weight (Kilograms)                 0
Freight Cost (USD)                 0
Line Item Insurance (USD)        287
dtype: int64

In [96]:
df = df.drop(['ID','Project Code',
    'PQ #',
    'PO / SO #',
    'ASN/DN #',
    'Managed By',
    'Fulfill Via',
    'Vendor INCO Term',
    'PQ First Sent to Client Date',
    'PO Sent to Vendor Date',
    'Scheduled Delivery Date',
    'Delivered to Client Date',
    'Delivery Recorded Date',
    'Product Group',
    'Sub Classification',
    'Vendor',
    'Item Description',
    'Molecule/Test Type',
    'Dosage',
    'Dosage Form',
    'Manufacturing Site',
    'First Line Designation',
], axis=1)
df

,Country,Shipment Mode,Brand,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,Côte d'Ivoire,Air,Reveal,30,19,551.00,29.00,0.97,13,780.34,NaN
1,Vietnam,Air,Generic,240,1000,6200.00,6.20,0.03,358,4521.5,NaN
2,Côte d'Ivoire,Air,Determine,100,500,40000.00,80.00,0.80,171,1653.78,NaN
3,Vietnam,Air,Generic,60,31920,127360.80,3.99,0.07,1855,16007.06,NaN
4,Vietnam,Air,Generic,60,38000,121600.00,3.20,0.05,7590,45450.08,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10319,Zimbabwe,Truck,Generic,60,166571,599655.60,3.60,0.06,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79
10320,Côte d'Ivoire,Truck,Generic,60,21072,137389.44,6.52,0.11,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71
10321,Zambia,Truck,Generic,30,514526,5140114.74,9.99,0.33,Weight Captured Separately,Freight Included in Commodity Cost,5284.04
10322,Zimbabwe,Truck,Generic,60,17465,113871.80,6.52,0.11,1392,Freight Included in Commodity Cost,134.03
10323,Zimbabwe,Truck,Generic,60,36639,72911.61,1.99,0.03,Weight Captured Separately,Freight Included in Commodity Cost,85.82

In [97]:
print("Number of columns in Data Frame----->\n",df.columns, end=" \n \n")
print("Data Types in Data Frame \n \n",df.dtypes)

Number of columns in Data Frame----->
 Index(['Country', 'Shipment Mode', 'Brand', 'Unit of Measure (Per Pack)',
       'Line Item Quantity', 'Line Item Value', 'Pack Price', 'Unit Price',
       'Weight (Kilograms)', 'Freight Cost (USD)',
       'Line Item Insurance (USD)'],
      dtype='object')

Data Types in Data Frame

 Country                        object
Shipment Mode                  object
Brand                          object
Unit of Measure (Per Pack)      int64
Line Item Quantity              int64
Line Item Value               float64
Pack Price                    float64
Unit Price                    float64
Weight (Kilograms)             object
Freight Cost (USD)             object
Line Item Insurance (USD)     float64
dtype: object

In [98]:
print("Unique Country names:- \n \n",df['Country'].unique())

country_dict = {
    "India" : 91,
    "Côte d'Ivoire" : 255,
    "Vietnam" : 84,
    "Nigeria" : 234,
    "Zambia" : 260,
    "Tanzania" : 255,
    "Rwanda" : 250,
    "Haiti" : 509,
    "Zimbabwe" : 263,
    "Ethiopia" :251,
    "outh Africa" : 27,
    "Guyana" : 592,
    "Namibia" : 264,
    "Botswana" : 267,
    "Mozambique" : 258,
    "Kenya" : 254,
    "Kazakhstan" : 7,
    "Uganda" : 256,
    "Kyrgyzstan" : 996,
    "Senegal" : 221,
    "Benin" : 229,
    "Lesotho" : 266,
    "Pakistan" : 92,
    "Swaziland" : 268,
    "Ghana" : 233,
    "Angola" : 244,
    "Lebanon" : 961,
    "Sierra Leone" : 232,
    "Cameroon" : 237,
    "South Sudan" : 211,
    "Burundi" : 257,
    "Dominican Republic" : 1,
    "Malawi" : 265,
    "Congo RDC" : 243,
    "Sudan" : 249,
    "Mali" : 223,
    "Guatemala" : 502,
    "Togo" : 228,
    "Afghanistan" : 93,
    "Liberia" : 231,
    "Burkina Faso" : 226,
    "Guinea" : 224,
    "Libya" : 218,
    "Belize" : 501,
}

Unique Country names:-

 ["Côte d'Ivoire" 'Vietnam' 'Nigeria' 'Zambia' 'Tanzania' 'Rwanda' 'Haiti'
 'Zimbabwe' 'Ethiopia' 'South Africa' 'Guyana' 'Namibia' 'Botswana'
 'Mozambique' 'Kenya' 'Kazakhstan' 'Uganda' 'Kyrgyzstan' 'Senegal' 'Benin'
 'Lesotho' 'Pakistan' 'Swaziland' 'Ghana' 'Angola' 'Lebanon'
 'Sierra Leone' 'Cameroon' 'South Sudan' 'Burundi' 'Dominican Republic'
 'Malawi' 'Congo, DRC' 'Sudan' 'Mali' 'Guatemala' 'Togo' 'Afghanistan'
 'Liberia' 'Burkina Faso' 'Guinea' 'Libya' 'Belize']

In [99]:
df['Country'] = df['Country'].map(country_dict)

In [106]:
print(df['Shipment Mode'].unique())
print(df['Shipment Mode'].isnull().sum())

shipmode_dict = {
    'nan' : 0,
    "Air" : 1,
    "Truck" : 2,
    "Air Charter" : 3,
    "Ocean" : 4
}
df['Shipment Mode'] = df['Shipment Mode'].map(shipmode_dict)
print(df.dtypes)
df

[nan]
10324
Country                       float64
Shipment Mode                 float64
Brand                          object
Unit of Measure (Per Pack)      int64
Line Item Quantity              int64
Line Item Value               float64
Pack Price                    float64
Unit Price                    float64
Weight (Kilograms)             object
Freight Cost (USD)             object
Line Item Insurance (USD)     float64
dtype: object